// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Prefer DIRECT_URL for migrate deploy against Supabase (non-pooler).
    // App runtime still uses DATABASE_URL via lib/db.ts.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
